# Generated by Django 4.0.6 on 2022-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_size',
            field=models.IntegerField(blank=True, help_text="Please specify video length in MB's.", null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.IntegerField(blank=True, help_text='Please specify video length in seconds.', null=True),
        ),
    ]
