# Generated by Django 4.0.6 on 2022-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_video_video_url_video_video_video_video_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_size',
            field=models.FloatField(blank=True, help_text="Please specify video length in MB's.", null=True),
        ),
    ]
